version:  '3.3'

services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: feelit
    networks:
      testing_net:
        ipv4_address: 172.24.0.2

  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - './../apps/:/apps'
      - './docker/nginx/feelit.local.conf:/etc/nginx/conf.d/feelit.local.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php
    networks:
      testing_net:
        ipv4_address: 172.24.0.3

  php:
    build:
      context: docker
      dockerfile: php/Dockerfile
    volumes:
      - './../apps/:/apps'
    restart: on-failure
    env_file:
      - docker/.env
    user: 738240311:738240311
    networks:
      testing_net:
        ipv4_address: 172.24.0.4

  rabbitmq:
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq.feelit.local
    build:
      context: ./docker/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    labels:
      NAME: "rabbitmq1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "WEREEDREDREWWWERDWDREEDDW"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - "./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./docker/rabbitmq/entrypoint.sh:/etc/rabbitmq/entrypoint.sh"
    networks:
      testing_net:
        ipv4_address: 172.24.0.5
    entrypoint:
      - /bin/sh
      - /etc/rabbitmq/entrypoint.sh
      - /usr/local/bin/docker-entrypoint.sh
      - rabbitmq-server

networks:
  testing_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16